---
- name: Firewll server installed
  hosts: web

  tasks:
  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started
      
