---
- name: Apache server ports in firewalld conf remove  
  hosts: app-nodes
  tasks:
  - name: firewalld ports removal for web service
    firewalld:
      service: "{{ item }}"
      permanent: false
      state: absent
      immediate: yes
    with_items:
      - http
      - https
