---
- name: Apache server ports in firewalld setup 
  hosts: web

  tasks:
  - name: firewalld permits https service
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
      immediate: yes
    with_items:
      - http
      - https
